<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OpenDispatch.Domain</RootNamespace>
    <AssemblyName>OpenDispatch.Domain</AssemblyName>
  </PropertyGroup>

</Project>
