// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenDispatch.Infrastructure.Persistence;

#nullable disable

namespace OpenDispatch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810133058_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenDispatch.Domain.Assignments.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTimeOffset>("ScheduledStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<double>("TravelMin")
                        .HasColumnType("double precision")
                        .HasColumnName("travel_min");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_assignments_job_id");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_assignments_org_id");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Contact", "OpenDispatch.Domain.Customers.Customer.Contact#ContactInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .HasColumnType("text")
                                .HasColumnName("contact_email");

                            b1.Property<string>("Phone")
                                .HasColumnType("text")
                                .HasColumnName("contact_phone");
                        });

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_customers_org_id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Domain.Invoices.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Issued")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_invoices_org_id");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Domain.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<TimeSpan>("EstimatedDuration")
                        .HasColumnType("interval")
                        .HasColumnName("estimated_duration");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (Point,4326)")
                        .HasColumnName("location");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("RequiredSkill")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required_skill");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Window", "OpenDispatch.Domain.Jobs.Job.Window#TimeWindow", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("window_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("window_start");
                        });

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_jobs_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_jobs_org_id");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Domain.Technicians.Technician", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Point>("HomeBase")
                        .IsRequired()
                        .HasColumnType("geography (Point,4326)")
                        .HasColumnName("home_base");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string[]>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skills");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Shift", "OpenDispatch.Domain.Technicians.Technician.Shift#TimeWindow", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("shift_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("shift_start");
                        });

                    b.HasKey("Id")
                        .HasName("pk_technicians");

                    b.HasIndex("HomeBase")
                        .HasDatabaseName("ix_technicians_home_base");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HomeBase"), "gist");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_technicians_org_id");

                    b.ToTable("technicians", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Domain.Customers.Customer", b =>
                {
                    b.OwnsMany("OpenDispatch.Domain.Customers.ServiceLocation", "Locations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("label");

                            b1.Property<Point>("Point")
                                .IsRequired()
                                .HasColumnType("geography (Point,4326)")
                                .HasColumnName("point");

                            b1.HasKey("Id")
                                .HasName("pk_service_locations");

                            b1.HasIndex("CustomerId")
                                .HasDatabaseName("ix_service_locations_customer_id");

                            b1.HasIndex("Point")
                                .HasDatabaseName("ix_service_locations_point");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("Point"), "gist");

                            b1.ToTable("service_locations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId")
                                .HasConstraintName("fk_service_locations_customers_customer_id");
                        });

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("OpenDispatch.Domain.Invoices.Invoice", b =>
                {
                    b.OwnsMany("OpenDispatch.Domain.Invoices.LineItem", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("description");

                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uuid")
                                .HasColumnName("invoice_id");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer")
                                .HasColumnName("kind");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric")
                                .HasColumnName("quantity");

                            b1.Property<long>("UnitPrice")
                                .HasColumnType("bigint")
                                .HasColumnName("unit_price");

                            b1.HasKey("Id")
                                .HasName("pk_line_items");

                            b1.HasIndex("InvoiceId")
                                .HasDatabaseName("ix_line_items_invoice_id");

                            b1.ToTable("line_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId")
                                .HasConstraintName("fk_line_items_invoices_invoice_id");
                        });

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
