// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenDispatch.Infrastructure.Persistence;

#nullable disable

namespace OpenDispatch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenDispatch.Application.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<long>("ChangeSeq")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("change_seq")
                        .HasDefaultValueSql("pg_current_xact_id()::text::bigint");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Targets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("targets");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("OrgId", "At")
                        .HasDatabaseName("ix_audit_entries_org_id_at");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Application.Auth.AuthUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChangeSeq")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("change_seq")
                        .HasDefaultValueSql("pg_current_xact_id()::text::bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_users_org_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Application.Sync.SyncOpRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<long>("BaseVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("base_version");

                    b.Property<long>("ChangeSeq")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("change_seq")
                        .HasDefaultValueSql("pg_current_xact_id()::text::bigint");

                    b.Property<DateTimeOffset>("ClientTs")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("client_ts");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_sync_ops");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_sync_ops_org_id");

                    b.ToTable("sync_ops", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Application.Sync.SyncRemoval", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<long>("ChangeSeq")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("change_seq")
                        .HasDefaultValueSql("pg_current_xact_id()::text::bigint");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTimeOffset>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.HasKey("EntityId")
                        .HasName("pk_sync_removals");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_sync_removals_org_id");

                    b.HasIndex("TechnicianId")
                        .HasDatabaseName("ix_sync_removals_technician_id");

                    b.ToTable("sync_removals", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Domain.Assignments.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChangeSeq")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("change_seq")
                        .HasDefaultValueSql("pg_current_xact_id()::text::bigint");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTimeOffset>("ScheduledStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<double>("TravelMin")
                        .HasColumnType("double precision")
                        .HasColumnName("travel_min");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_assignments_job_id");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_assignments_org_id");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Domain.Attachments.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_length");

                    b.Property<long>("ChangeSeq")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("change_seq")
                        .HasDefaultValueSql("pg_current_xact_id()::text::bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_attachments_job_id");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_attachments_org_id");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChangeSeq")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("change_seq")
                        .HasDefaultValueSql("pg_current_xact_id()::text::bigint");

                    b.Property<DateTimeOffset?>("ErasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("erased_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Contact", "OpenDispatch.Domain.Customers.Customer.Contact#ContactInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .HasColumnType("text")
                                .HasColumnName("contact_email");

                            b1.Property<string>("Phone")
                                .HasColumnType("text")
                                .HasColumnName("contact_phone");
                        });

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_customers_org_id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Domain.Invoices.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChangeSeq")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("change_seq")
                        .HasDefaultValueSql("pg_current_xact_id()::text::bigint");

                    b.Property<DateTimeOffset>("Issued")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_invoices_org_id");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Domain.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChangeSeq")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("change_seq")
                        .HasDefaultValueSql("pg_current_xact_id()::text::bigint");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("ErasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("erased_at");

                    b.Property<TimeSpan>("EstimatedDuration")
                        .HasColumnType("interval")
                        .HasColumnName("estimated_duration");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (Point,4326)")
                        .HasColumnName("location");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("NotesRecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notes_recorded_at");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("RequiredSkill")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required_skill");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Window", "OpenDispatch.Domain.Jobs.Job.Window#TimeWindow", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("window_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("window_start");
                        });

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_jobs_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_jobs_org_id");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChangeSeq")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("change_seq")
                        .HasDefaultValueSql("pg_current_xact_id()::text::bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Domain.Technicians.Technician", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChangeSeq")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("change_seq")
                        .HasDefaultValueSql("pg_current_xact_id()::text::bigint");

                    b.Property<Point>("HomeBase")
                        .IsRequired()
                        .HasColumnType("geography (Point,4326)")
                        .HasColumnName("home_base");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<string[]>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skills");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Shift", "OpenDispatch.Domain.Technicians.Technician.Shift#TimeWindow", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("shift_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("shift_start");
                        });

                    b.HasKey("Id")
                        .HasName("pk_technicians");

                    b.HasIndex("HomeBase")
                        .HasDatabaseName("ix_technicians_home_base");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HomeBase"), "gist");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_technicians_org_id");

                    b.ToTable("technicians", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Infrastructure.Events.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<long>("ChangeSeq")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("change_seq")
                        .HasDefaultValueSql("pg_current_xact_id()::text::bigint");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_occurred_at");

                    b.HasIndex("OrgId", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_org_id_occurred_at");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("OpenDispatch.Domain.Customers.Customer", b =>
                {
                    b.OwnsMany("OpenDispatch.Domain.Customers.ServiceLocation", "Locations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address");

                            b1.Property<long>("ChangeSeq")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("bigint")
                                .HasColumnName("change_seq")
                                .HasDefaultValueSql("pg_current_xact_id()::text::bigint");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("label");

                            b1.Property<Point>("Point")
                                .IsRequired()
                                .HasColumnType("geography (Point,4326)")
                                .HasColumnName("point");

                            b1.HasKey("Id")
                                .HasName("pk_service_locations");

                            b1.HasIndex("CustomerId")
                                .HasDatabaseName("ix_service_locations_customer_id");

                            b1.HasIndex("Point")
                                .HasDatabaseName("ix_service_locations_point");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("Point"), "gist");

                            b1.ToTable("service_locations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId")
                                .HasConstraintName("fk_service_locations_customers_customer_id");
                        });

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("OpenDispatch.Domain.Invoices.Invoice", b =>
                {
                    b.OwnsMany("OpenDispatch.Domain.Invoices.LineItem", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<long>("ChangeSeq")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("bigint")
                                .HasColumnName("change_seq")
                                .HasDefaultValueSql("pg_current_xact_id()::text::bigint");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("description");

                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uuid")
                                .HasColumnName("invoice_id");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer")
                                .HasColumnName("kind");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric")
                                .HasColumnName("quantity");

                            b1.Property<long>("UnitPrice")
                                .HasColumnType("bigint")
                                .HasColumnName("unit_price");

                            b1.HasKey("Id")
                                .HasName("pk_line_items");

                            b1.HasIndex("InvoiceId")
                                .HasDatabaseName("ix_line_items_invoice_id");

                            b1.ToTable("line_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId")
                                .HasConstraintName("fk_line_items_invoices_invoice_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("OpenDispatch.Domain.Jobs.Job", b =>
                {
                    b.OwnsMany("OpenDispatch.Domain.Jobs.JobLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("JobId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Description")
                                .IsRequired();

                            b1.Property<Guid>("Id");

                            b1.Property<int>("Kind");

                            b1.Property<decimal>("Quantity");

                            b1.Property<DateTimeOffset>("RecordedAt");

                            b1.Property<long>("UnitPrice");

                            b1.HasKey("JobId", "__synthesizedOrdinal")
                                .HasName("pk_jobs");

                            b1.ToTable("jobs");

                            b1
                                .ToJson("lines")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("JobId")
                                .HasConstraintName("fk_jobs_jobs_job_id");
                        });

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
